import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar/navabar";
import FallingBitcoinBackground from "./utility/Backgorundcover";
import Footer from "@/app/footer/footercomponent";
import { ClipLoader} from "react-spinners";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "BITSENSE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense fallback={<div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100vh' }}>
      <ClipLoader color="#36d7b7" loading={"loading"} size={50} />
    </div>}>
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
        </Suspense>
      
      </body>
    </html>
  );
}
